clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '

*.elf: $(wildcard D:/RT-ThreadStudioGG/repo/Extract/RT-Thread_Source_Code/RT-Thread/latest/rt-thread/bsp/stm32/stm32f767-fire-challenger/stm32f767/board/linker_scripts/link.lds)
